# Generated by Django 3.2.2 on 2022-02-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='province',
            name='alpha_code',
            field=models.CharField(max_length=150),
        ),
    ]
