# Generated by Django 3.2.2 on 2022-02-10 02:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_api', '0003_alter_province_alpha_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForwardSortationArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('health_regions', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), size=None)),
            ],
            options={
                'db_table': 'forward_sortation_area',
            },
        ),
    ]
