version: "3.8"
services:
  # web:
  #   build: .
  #   command: gunicorn nc_tutorials.wsgi:application --bind 0.0.0.0:8000
  #   volumes:
  # ports:
  #   - "8000:8000"
  # expose:
  #   - 8000
  #   environment:
  #     - DB_NAME=nc_tutorials_db
  #     - DB_USER=postgres
  #     - DB_PASSWORD=admin123
  #     - DB_HOST=nctutorials.cgscp9ckfghn.us-east-2.rds.amazonaws.com
  #     - DB_PORT=5432
  #     - DATABASE=postgres
  #     - VIRTUAL_HOST=ec2-3-128-61-120.us-east-2.compute.amazonaws.com
  #     - VIRTUAL_PORT=8000
  pg:
    container_name: pg_container
    image: postgres:13.2-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
      PGUSER: postgres
    ports:
      - "5432:5432"
    volumes:
      - "${PWD}/data/schema/init.sql:/docker-entrypoint-initdb.d/1-init.sql"
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:5.2
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: 123
      PGADMIN_LISTEN_PORT: 5433
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
      PGADMIN_CONFIG_UPGRADE_CHECK_ENABLED: "False"
    ports:
      - "5433:5433"
    depends_on:
      - pg
networks:
  default:
    name: nunet
