# Generated by Django 3.2.2 on 2022-03-25 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'country',
            },
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=150)),
                ('classification', models.CharField(blank=True, max_length=150)),
                ('subclassification', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'db_table': 'disease',
            },
        ),
        migrations.CreateModel(
            name='HealthRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hr_uid', models.PositiveSmallIntegerField()),
                ('name_en', models.CharField(max_length=150)),
                ('name_fr', models.CharField(max_length=150)),
                ('website_en', models.CharField(max_length=300)),
                ('website_fr', models.CharField(max_length=300)),
                ('disease', models.ManyToManyField(blank=True, to='api.Disease')),
            ],
            options={
                'db_table': 'health_region',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=150)),
                ('name_fr', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'region',
            },
        ),
        migrations.CreateModel(
            name='WeatherStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField()),
                ('fk_health_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.healthregion')),
            ],
            options={
                'db_table': 'weather_station',
            },
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccination_name', models.CharField(max_length=150)),
                ('efficacy_rate', models.PositiveSmallIntegerField(blank=True)),
                ('percent_pop_vaccinated', models.PositiveSmallIntegerField(blank=True)),
                ('treats_disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.disease')),
            ],
            options={
                'db_table': 'vaccination',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geo_code', models.CharField(choices=[('10', 'Newfoundland and Labrador'), ('11', 'Prince Edward Island'), ('12', 'Nova Scotia'), ('13', 'New Brunswick'), ('24', 'Quebec'), ('35', 'Ontario'), ('46', 'Manitoba'), ('47', 'Saskatchewan'), ('48', 'Alberta'), ('59', 'British Columbia'), ('60', 'Yukon'), ('61', 'Northwest Territories')], max_length=2)),
                ('alpha_code', models.CharField(choices=[('NL', 'Newfoundland and Labrador'), ('PE', 'Prince Edward Island'), ('NS', 'Nova Scotia'), ('NB', 'New Brunswick'), ('QC', 'Quebec'), ('ON', 'Ontario'), ('MB', 'Manitoba'), ('SK', 'Saskatchewan'), ('AB', 'Alberta'), ('BC', 'British Columbia'), ('YT', 'Yukon'), ('NT', 'Northwest Territories')], max_length=2)),
                ('name_en', models.CharField(max_length=150)),
                ('name_fr', models.CharField(max_length=150)),
                ('disease', models.ManyToManyField(blank=True, to='api.Disease')),
                ('fk_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.region')),
            ],
            options={
                'db_table': 'province',
            },
        ),
        migrations.AddField(
            model_name='healthregion',
            name='fk_province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.province'),
        ),
        migrations.CreateModel(
            name='ForwardSortationArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('disease', models.ManyToManyField(blank=True, to='api.Disease')),
                ('fk_province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.province')),
            ],
            options={
                'db_table': 'forward_sortation_area',
            },
        ),
    ]
