# Generated by Django 3.2.2 on 2022-02-07 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Health_Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hr_uid', models.PositiveSmallIntegerField()),
                ('fk_province_code', models.PositiveSmallIntegerField()),
                ('name_en', models.CharField(max_length=150)),
                ('name_fr', models.CharField(max_length=150)),
                ('website_en', models.CharField(max_length=300)),
                ('website_fr', models.CharField(max_length=300)),
            ],
        ),
    ]
